FROM ghcr.io/jorgensd/dolfinx_mpc:v0.9.3

LABEL \
  maintainer- \
  description- \
  org.opencontainers.image.title="Distributed two-scale method library" \
  org.opencontainers.image.description="A library that implements the distributed two-scale method adapted to FEniCSx/PETSc usage." \
  org.opencontainers.image.authors="Alexis Salzman (alexis.salzman@ec-nantes.fr)" \
  org.opencontainers.image.vendor="Nantes université, Ecole centrale de Nantes, GeM Institute, UMR CNRS 6180, 1 rue de la Noë, 44321, Nantes, France" \
  org.opencontainers.image.licenses="GNU LGPL-3.0"


WORKDIR /workspace

COPY cpp cpp
COPY python python
COPY docs/requirements.txt .

# Build and install the C++ library
RUN cmake -S cpp -B build-cpp \
       -DCMAKE_BUILD_TYPE=Release \
       -DCMAKE_INSTALL_PREFIX=/usr/local\
       -DCMAKE_INSTALL_LIBDIR=/usr/local/lib
RUN cmake --build build-cpp 
RUN cmake --install build-cpp

# Build and install the Python package
WORKDIR /workspace/python
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install --no-build-isolation .

# only if build went well add requirement for doc
WORKDIR /workspace
RUN python3 -m pip install  -r requirements.txt

